### ISSUE TITLE
how to use red_loop

### ISSUE THREAD

**Issue by zambofd** [wangqinhu/red_loop#1]
Hi~,I am interested in these scripts, but I don't know how to use them. May i have a brief introduction? Thank you first.

**Comment by wangqinhu** [comment]
Hi @zambofd ,

You can clone this repo and type `perl ./structure_bias.pl <refseq.fasta> <flank_seq_length>` in the terminal.
eg. `perl ./structure_bias.pl genome.fa 30`
Other scripts are used for making figures
I will add a README for these scripts in 1-2 weeks.

Qinhu

**Comment by zambofd** [comment]
Thank you very much.



ybzhang

在 2017-11-18 00:39:37，"Qinhu Wang" <notifications@github.com> 写道：


Hi @zambofd ,

You can clone this repo and type perl ./structure_bias.pl <refseq.fasta> <flank_seq_length> in the terminal.
eg. perl ./structure_bias.pl genome.fa 30
Other scripts are used for making figures
I will add a README for these scripts in 1-2 weeks.

Qinhu
